### ISSUE TITLE
Release new version on PyPi

### ISSUE THREAD

**Issue by grafail** [smazzanti/mrmr#25]
The latest version currently available on PyPi (https://pypi.org/project/mrmr-selection/) has the issue mentioned in #23, which creates installation issues in specific cases.

**Comment by enryH** [comment]
yes this would be great. Trying to install from git directly also fails currently due to a missing build dependency (which is a required package for `mrmr`):

```
>>> pip install git+https://github.com/smazzanti/mrmr.git
Collecting git+https://github.com/smazzanti/mrmr.git
  Cloning https://github.com/smazzanti/mrmr.git to /tmp/pip-req-build-pd3v7a6j
  Running command git clone --filter=blob:none --quiet https://github.com/smazzanti/mrmr.git /tmp/pip-req-build-pd3v7a6j
  Resolved https://github.com/smazzanti/mrmr.git to commit 688b5e75fbb43a6d95d8705e619f39a5b9f4b810
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-pd3v7a6j/setup.py", line 2, in <module>
          from mrmr import __version__
        File "/tmp/pip-req-build-pd3v7a6j/mrmr/__init__.py", line 2, in <module>
          from . import pandas
        File "/tmp/pip-req-build-pd3v7a6j/mrmr/pandas.py", line 6, in <module>
          import category_encoders as ce
      ModuleNotFoundError: No module named 'category_encoders'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

>>> pip --version
pip 22.3.1
```

**Comment by enryH** [comment]
The error rates will overwise increase, until it it will always raise an error: https://pypi.org/project/sklearn/

**Comment by smazzanti** [comment]
Thank you for pointing out. The latest version on PyPi (0.2.6) has now scikit-learn instead of sklearn, so this is fixed.
