### ISSUE TITLE
Problem to install library

### ISSUE THREAD

**Issue by antoniotdelend** [smazzanti/mrmr#33]
` pip install mrmr
Collecting mrmr
  Using cached mrmr-0.9.2.tar.gz (18 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\anton\AppData\Local\Temp\pip-install-zngtmzxk\mrmr_a64358380c864590abc49eb48cf68abc\setup.py", line 9, in <module>
          from mrmr import __version__ as _mrmr_version
        File "C:\Users\anton\AppData\Local\Temp\pip-install-zngtmzxk\mrmr_a64358380c864590abc49eb48cf68abc\lib\mrmr\__init__.py", line 5, in <module>
          from ._discretemrmr import *
        File "C:\Users\anton\AppData\Local\Temp\pip-install-zngtmzxk\mrmr_a64358380c864590abc49eb48cf68abc\lib\mrmr\_discretemrmr.py", line 31, in <module>
          from fakemp import farmout, farmworker
      ModuleNotFoundError: No module named 'fakemp'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

**Comment by YsabelleSousa** [comment]
@antoniotdelend The correct lib's name is mrmr_selection. So, if you run the command below, it should work:

`pip install mrmr_selection`
