### ISSUE TITLE
A task has failed to un-serialize. 

### ISSUE THREAD

**Issue by leummas** [smazzanti/mrmr#38]
Running the example code Im receiving the following error:

---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/conda/envs/feature_creation_env/lib/python3.12/site-packages/joblib/externals/loky/process_executor.py", line 426, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/feature_creation_env/lib/python3.12/multiprocessing/queues.py", line 122, in get
    return _ForkingPickler.loads(res)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/feature_creation_env/lib/python3.12/site-packages/mrmr/__init__.py", line 1, in <module>
    from . import bigquery
  File "/opt/conda/envs/feature_creation_env/lib/python3.12/site-packages/mrmr/bigquery.py", line 3, in <module>
    from .main import mrmr_base, groupstats2fstat
  File "/opt/conda/envs/feature_creation_env/lib/python3.12/site-packages/mrmr/main.py", line 1, in <module>
    import pandas as pd
  File "/opt/conda/envs/feature_creation_env/lib/python3.12/site-packages/pandas/__init__.py", line 46, in <module>
    from pandas.core.api import (
  File "/opt/conda/envs/feature_creation_env/lib/python3.12/site-packages/pandas/core/api.py", line 47, in <module>
    from pandas.core.groupby import (
  File "/opt/conda/envs/feature_creation_env/lib/python3.12/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/opt/conda/envs/feature_creation_env/lib/python3.12/site-packages/pandas/core/groupby/generic.py", line 67, in <module>
    from pandas.core.frame import DataFrame
...
--> [754](https://vscode-remote+ssh-002dremote-002bcompute-002e5075729831712098424.vscode-resource.vscode-cdn.net/opt/conda/envs/feature_creation_env/lib/python3.12/site-packages/joblib/parallel.py:754)         raise self._result
    [755](https://vscode-remote+ssh-002dremote-002bcompute-002e5075729831712098424.vscode-resource.vscode-cdn.net/opt/conda/envs/feature_creation_env/lib/python3.12/site-packages/joblib/parallel.py:755)     return self._result
    [756](https://vscode-remote+ssh-002dremote-002bcompute-002e5075729831712098424.vscode-resource.vscode-cdn.net/opt/conda/envs/feature_creation_env/lib/python3.12/site-packages/joblib/parallel.py:756) finally:

BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.

**Comment by benhorvath** [comment]
I am also getting a similar error, with both classification and regression functions.
